# Generated by Django 6.0.6 on 2026-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('exp_type', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional'), ('project', 'Project')], default='project', max_length=20)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
