# Generated by Django 6.0.6 on 2026-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bio',
            name='hero_text',
            field=models.TextField(default='Welcome to my portfolio', help_text='Short text shown on home section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.TextField(help_text='Full bio shown in Bio section'),
        ),
    ]
